# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0011_remove_answer_title'),
        ('reco', '0012_comment'),
    ]

    operations = [
    ]
